name: Copyright Check

on:
  push:
    branches: [ "feature/workflow_test" ]
  pull_request:
    branches: [ "feature/workflow_test" ]
jobs:
        
  run-copyright-check:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout Code
       uses: actions/checkout@v4
     - name: Copyright Comment Check
       uses: liquiddevelopmentnet/copyright-check-action@stable-1.0
       with:
        path: src/**/*.java
        string:// Copyright (c) 2025 Sampath Bank PLC. All rights reserved.
