name: Lint & Copyright Check on Codebase

on:
  push:
    branches: [ "feature/workflow_test" ]
  pull_request:
    branches: [ "feature/workflow_test" ]
jobs:
        
  run-copyright-check:
    runs-on: ubuntu-latest
    steps:
     - name: Copyright Comment Check
       uses: liquiddevelopmentnet/copyright-check-action@stable-1.0
       with:
        # In which path you wanna check
        path: src/**/*.java
        # For what should the action check
        string: // Copyright (C) 2021 Example, Inc. All Rights reserved.
  
